package com.particlesdevs.photoncamera.debugclient;

//Keys
//CHARACTERISTICS_KEY
//CHARACTERISTICS_KEYS
//CAPTURE_KEYS
//BUILDER_CREATE
//BUILDER_SET
//PREVIEW_KEY
//PREVIEW_KEYS
//PREVIEW_KEYS_PRINT
//DEBUG_SHOT
enum KeyWord {
    CHARACTERISTICS_KEY, CHARACTERISTICS_KEYS, CAPTURE_KEYS, BUILDER_CREATE,
    BUILDER_SET, PREVIEW_KEY, PREVIEW_KEYS, PREVIEW_REQUEST_KEYS, PREVIEW_REQUEST_KEYS_PRINT,
    PREVIEW_KEYS_PRINT, DEBUG_SHOT;
}
