package com.particlesdevs.photoncamera.processing.opengl.postpipeline;

import android.graphics.Bitmap;
import android.graphics.Point;
import android.opengl.GLES30;
import com.particlesdevs.photoncamera.util.Log;

import static android.opengl.GLES31.GL_CLAMP_TO_EDGE;
import static android.opengl.GLES31.GL_LINEAR;

import com.particlesdevs.photoncamera.api.CameraMode;
import com.particlesdevs.photoncamera.app.PhotonCamera;
import com.particlesdevs.photoncamera.processing.ImageFrame;
import com.particlesdevs.photoncamera.processing.opengl.GLBasePipeline;
import com.particlesdevs.photoncamera.processing.opengl.GLCoreBlockProcessing;
import com.particlesdevs.photoncamera.processing.opengl.GLDrawParams;
import com.particlesdevs.photoncamera.processing.opengl.GLFormat;
import com.particlesdevs.photoncamera.processing.opengl.GLImage;
import com.particlesdevs.photoncamera.processing.opengl.GLInterface;
import com.particlesdevs.photoncamera.processing.opengl.GLProg;
import com.particlesdevs.photoncamera.processing.opengl.GLTexture;
import com.particlesdevs.photoncamera.processing.opengl.postpipeline.RotateWatermark;
import com.particlesdevs.photoncamera.processing.opengl.scripts.GLHistogram;
import com.particlesdevs.photoncamera.processing.parameters.ResolutionSolution;
import com.particlesdevs.photoncamera.processing.render.NoiseModeler;
import com.particlesdevs.photoncamera.processing.render.Parameters;
import com.particlesdevs.photoncamera.processing.ultrahdr.GainMapComputer;
import com.particlesdevs.photoncamera.settings.annotations.Tunable;
import com.particlesdevs.photoncamera.util.Allocator;
import com.particlesdevs.photoncamera.util.BufferUtils;

import java.nio.ByteBuffer;
import java.util.ArrayList;

public class PostPipeline extends GLBasePipeline {
    public ByteBuffer stackFrame;
    public ByteBuffer lowFrame;
    public ByteBuffer highFrame;
    public GLTexture FusionMap;
    public GLTexture GainMap;
    /**
     * Linear display gain estimated by {@link LinearExposure} from the linear
     * histogram (motionv2 percentile scheme); consumed by {@link HeadroomRender}.
     */
    public float linearDisplayGain = 1.0f;
    /**
     * Scene (pre-exposure linear) luma that the SDR tone mapping maps to
     * display white; consumed by {@link #RunHDRGainMap} as the gain-map
     * anchor so the map pushes exactly the recoverable headroom above scene
     * white instead of the SDR median (which moves with the exposure choice).
     * 0 when no tonemapping white point is known -> median-anchor fallback.
     */
    public float sceneWhiteRaw = 0f;
    /**
     * Display-domain exposure curve (1D float LUT) generated by
     * {@link AutoExposureCurve} from the linear histogram; sampled by
     * {@link Initial} at the end of its shader (EXPOCURVE path) and closed in
     * Initial.AfterRun. Null when the curve-based AE node did not run.
     */
    public GLTexture exposureCurve;
    /**
     * Adaptive white point scalar produced by {@link AutoExposureCurve}: the
     * linear position of the measured scene white above display white on HDR
     * scenes (>= 1.0; 1.0 when whites already sit at display white). Passed by
     * {@link Initial} to initial.glsl, which divides its input by it so whites
     * anchor at 1.0 before the SDR tone chain - the AE estimates its exposure
     * curve on the same divided domain.
     */
    public float adaptiveWhitePoint = 1.0f;
    /**
     * Effective clip level of the CFA buffer produced by Bayer2Float: 1.0
     * when nothing is reconstructed, otherwise the white-balanced clip
     * extent (1/min(whitePoint)) that the inpaint-opposed reconstruction can
     * emit. Downstream nodes that treat values above the clip level as
     * clipped sensor data (Amaze's saturation bounding) read this instead of
     * assuming 1.0, so reconstructed photosites are interpolated normally.
     */
    public float rawClipLevel = 1.0f;
    public ArrayList<Bitmap> debugData = new ArrayList<>();
    public ArrayList<ImageFrame> SAGAIN;
    public Point cropSize;
    public float[] analyzedBL = new float[]{0.f, 0.f, 0.f};
    float regenerationSense = 1.f;
    float totalGain = 1.f;
    float AecCorr = 1.f;
    float fusionGain = 1.f;
    float softLight = 1.f;

    // Ultra HDR state.
    /**
     * When true, the first run captures the linear (post-demosaic) buffer so
     * the scene-anchored gain-map pass can measure pre-local-tone-map scene
     * energy.
     */
    public boolean captureDemosaic = false;
    private boolean mCaptured = false;
    /** Whether {@link #demosaicLinear} holds packed half-floats instead of 32-bit floats. */
    private boolean demosaicLinearHalfFloat = false;
    /**
     * CPU copy of the post-demosaic linear buffer (survives GLTexture.closeAll).
     * Backed by a native {@link Allocator} malloc and stored as packed
     * half-floats when the driver allows (the source texture is RGBA16F, so
     * nothing is lost) - 8 B/pixel, ~515 MB at 64 MP. Must be freed via
     * {@link #releaseDemosaicLinear()}.
     */
    public ByteBuffer demosaicLinear;
    public Point demosaicLinearSize;

    public PostPipeline() {
        super("PostPipeline");
    }

    public int getRotation() {
        int rotation = mParameters.cameraRotation;
        String TAG = "ParseExif";
        Log.d(TAG, "Gravity rotation:" + PhotonCamera.getGravity().getRotation());
        Log.d(TAG, "Sensor rotation:" + PhotonCamera.getCaptureController().mSensorOrientation);
        return rotation;
    }

    @SuppressWarnings("SuspiciousNameCombination")
    private Point getRotatedCoords(Point in) {
        switch (getRotation()) {
            case 0:
            case 180:
                return in;
            case 90:
            case 270:
                return new Point(in.y, in.x);
        }
        return in;
    }

    float constShift = 0.0f;

    @Tunable(
        title = "Demosaicing Method",
        description = "0 = Demosaic (compatibility mode), 1 = New demosaicing (better quality)",
        category = "Demosaic",
        min = 0.0f,
        max = 1.0f,
        defaultValue = 1.0f,
        step = 1.0f
    )
    int demosaicingMethod = 1;

    @Tunable(
        title = "Tone Pipeline",
        description = "Curve: AutoExposureCurve bakes an exposure curve consumed by Initial; Sky: linear-histogram exposure + log-headroom tone mapping; Off: no tone/color stage",
        category = "Color & Tone",
        entries = {"Curve (exposure curve into Initial)", "Sky (Headroom)", "New (simplified)", "Off (linear passthrough)"},
        entryValues = {"curve", "sky", "new", "off"}
    )
    String tonePipeline = "curve";

    @Tunable(
        title = "Upscale sharpen scale",
        description = "Scales Sharpen2 and CaptureSharpening strength for cropped (upscaled) captures; unsharp masks tuned for native detail overshoot on interpolated pixels, while the kernelnet reconstruction provides structure-aware acutance",
        category = "Upscale",
        min = 0.0f,
        max = 1.0f,
        defaultValue = 0.4f,
        step = 0.05f
    )
    float upscaleSharpenScale = 0.4f;

    private void computeNoise(Parameters parameters) {
        NoiseModeler modeler = parameters.noiseModeler;
        noiseS = modeler.computeModel[0].first.floatValue() +
                modeler.computeModel[1].first.floatValue() +
                modeler.computeModel[2].first.floatValue();
        noiseO = modeler.computeModel[0].second.floatValue() +
                modeler.computeModel[1].second.floatValue() +
                modeler.computeModel[2].second.floatValue();
        noiseS /= 3.f;
        noiseO /= 3.f;
        double noisempy = Math.pow(2.0, mSettings.noiseRstr + constShift);
        Log.d("PostPipeline", "noisempy:" + noisempy);
        noiseS *= noisempy;
        noiseO *= noisempy;
        Log.d("PostPipeline", "NoiseS:" + noiseS + "\n" + "NoiseO:" + noiseO);
        noiseO = Math.max(noiseO, Float.MIN_NORMAL);
        noiseS = Math.max(noiseS, Float.MIN_NORMAL);
    }

    public Bitmap Run(ByteBuffer inBuffer, Parameters parameters) {
        mParameters = parameters;
        mSettings = PhotonCamera.getSettings();
        Point rawSliced = parameters.rawSize;
        cropSize = new Point(parameters.rawSize);
        boolean zoomed = PhotonCamera.getCaptureController() != null
                && PhotonCamera.getCaptureController().zoomController.isZoomed();
        if (PhotonCamera.getSettings().aspect169 && !zoomed) {
            if (rawSliced.x > rawSliced.y) {
                rawSliced = new Point(rawSliced.x & ~3, (rawSliced.x * 9 / 16) & ~3);
            } else {
                rawSliced = new Point((rawSliced.y * 9 / 16) & ~3, rawSliced.y & ~3);
            }
            if (rawSliced.x < 4) rawSliced.x = 4;
            if (rawSliced.y < 4) rawSliced.y = 4;
            cropSize = new Point(rawSliced);
        }
        workSize = new Point(cropSize.x, cropSize.y);
        computeNoise(parameters);
        captureDemosaic = mSettings.ultraHdr;
        mCaptured = false;
        linearDisplayGain = 1.0f;
        sceneWhiteRaw = 0f;
        adaptiveWhitePoint = 1.0f;
        rawClipLevel = 1.0f;
        exposureCurve = null;
        Point targetSliced = new Point(rawSliced.x, rawSliced.y);
        if (parameters.fullRawSize != null && parameters.isCropped) {
            targetSliced = new Point(parameters.fullRawSize.x & ~3, parameters.fullRawSize.y & ~3);
        }
        Point rotatedSize = getRotatedCoords(targetSliced);
        if (PhotonCamera.getSettings().energySaving || mParameters.rawSize.x * mParameters.rawSize.y < ResolutionSolution.smallRes) {
            GLDrawParams.TileSize = 8;
        } else {
            GLDrawParams.TileSize = 256;
        }
        GLFormat format = new GLFormat(GLFormat.DataType.SIMPLE_8, 4);
        // The final bitmap is allocated up-front and the render is streamed
        // straight into its pixels: no intermediate full-frame native buffer
        // (~258 MB at 64 MP) and no extra copies.
        Bitmap res = Bitmap.createBitmap(rotatedSize.x, rotatedSize.y, Bitmap.Config.ARGB_8888);
        GLCoreBlockProcessing glproc = new GLCoreBlockProcessing(rotatedSize, null, format, GLDrawParams.Allocate.None);
        glint = new GLInterface(glproc);
        stackFrame = inBuffer;
        glint.parameters = parameters;

        // Inject tunable values for PostPipeline (since it doesn't extend Node)
        com.particlesdevs.photoncamera.settings.TunableInjector.inject(this);

        BuildDefaultPipeline();
        res = runAll(res);
        Allocator.logStage("PostPipeline", "post-render");

        // The linear scene buffer was already snapshotted to CPU from inside
        // Initial.Run (before closeAll claims the textures), so the
        // scene-anchored gain-map pass can measure it afterwards.
        // closeAll must run while the EGL context is still current.
        GLTexture.closeAll();
        return res;
    }

    /** KernelNet parameter map (RGBA floats: s1, s2, rho, 1) exported by ESD4D during the merge pass; may be null (single frame / model unavailable). */
    public java.nio.FloatBuffer kernelParams;
    /** Size of {@link #kernelParams}. */
    public android.graphics.Point kernelParamsSize;
    /** Worker thread running the single-frame KernelNet inference, started by KernelNetPrep and collected by UpscaleCrop; may be null. */
    public Thread kernelNetSingleThread;
    /** Result of the single-frame KernelNet inference; null until/unless it completes successfully. */
    public java.util.concurrent.atomic.AtomicReference<com.particlesdevs.photoncamera.processing.ml.KernelNetResult> kernelNetSingleResult =
            new java.util.concurrent.atomic.AtomicReference<>();

    /** Called from Initial.Run (first pass) to keep the linear scene buffer. */
    public void captureDemosaicLinear(GLTexture tex) {
        if (mCaptured || demosaicLinear != null) return;
        tex.BindBuffer();
        // The source texture is RGBA16F, so a packed GL_HALF_FLOAT transfer
        // stores the identical bits at half the memory of a GL_FLOAT readback
        // (~515 MB vs ~1030 MB at 64 MP). Backed by native memory either way;
        // fall back to 32-bit floats if the driver refuses the packed type.
        ByteBuffer buf = tex.textureBufferHalfFloat();
        if (buf != null) {
            demosaicLinearHalfFloat = true;
        } else {
            int size = tex.mSize.x * tex.mSize.y * 4 * 4;
            buf = Allocator.allocate(size);
            if (buf == null) {
                Log.e("PostPipeline", "Linear scene snapshot allocation of " + size + " B failed; Ultra HDR will fall back to SDR");
                return;
            }
            tex.textureBuffer(new GLFormat(GLFormat.DataType.FLOAT_16, 4), buf);
            buf.rewind();
            demosaicLinearHalfFloat = false;
        }
        demosaicLinear = buf;
        demosaicLinearSize = new Point(tex.mSize.x, tex.mSize.y);
        mCaptured = true;
    }

    /** Frees the native linear scene snapshot; safe to call repeatedly. */
    public void releaseDemosaicLinear() {
        if (demosaicLinear != null) {
            Allocator.free(demosaicLinear);
            demosaicLinear = null;
        }
        demosaicLinearSize = null;
    }

    /**
     * Ultra HDR gain-map pass (scene-anchored): fusion local tone mapping
     * compresses clipped highlights below display white inside the rendering
     * chain, so no comparison of pipeline outputs can recover them. Instead
     * this pass measures the pre-local-tone-map scene energy directly from the
     * captured post-demosaic buffer ({@link #demosaicLinear}):
     *
     * <ol>
     *   <li>render the scene-luma plane L (linear luminance, rotated/cropped to
     *       match the stored base) via {@code ultrahdr/sceneluma}</li>
     *   <li>anchor the two midtones to each other:
     *       {@code k = median(linearized base luma) / median(L)} - matching
     *       medians makes the scene/render ratio grow monotonically as the SDR
     *       signal saturates, so clipped cores always dominate</li>
     *   <li>encode {@code log2((L·k + eps) / (baseLuma + eps))} via
     *       {@code ultrahdr/gainmap}</li>
     * </ol>
     *
     * Scene content above the anchor with a saturated SDR signal yields real,
     * multi-stop boost; the anchor itself is exactly zero and everything below
     * is floored to identity. Independent of AutoExposure and local tone
     * mapping state.
     *
     * @param sdr   the SDR (display-encoded) base rendition, already computed by {@link #Run}
     * @param down  downsample factor per axis for the gain map (1/down^2 pixels)
     * @param scale total log2 range of the encoding; must equal {@link GainMapComputer#SCALE}
     * @return the encoded RGBA8 gain map plus its dimensions, downsample and scale
     */
    public GainMapRaw RunHDRGainMap(Parameters parameters, Bitmap sdr, int down, float scale) {
        if (demosaicLinear == null || demosaicLinearSize == null) {
            throw new IllegalStateException("Linear buffer missing; Run() must complete first with ultraHdr enabled");
        }
        mParameters = parameters;
        mSettings = PhotonCamera.getSettings();
        Point rawSliced = parameters.rawSize;
        cropSize = new Point(parameters.rawSize);
        boolean zoomed = PhotonCamera.getCaptureController() != null
                && PhotonCamera.getCaptureController().zoomController.isZoomed();
        if (PhotonCamera.getSettings().aspect169 && !zoomed) {
            if (rawSliced.x > rawSliced.y) {
                rawSliced = new Point(rawSliced.x & ~3, (rawSliced.x * 9 / 16) & ~3);
            } else {
                rawSliced = new Point((rawSliced.y * 9 / 16) & ~3, rawSliced.y & ~3);
            }
            if (rawSliced.x < 4) rawSliced.x = 4;
            if (rawSliced.y < 4) rawSliced.y = 4;
            cropSize = new Point(rawSliced);
        }
        workSize = new Point(cropSize.x, cropSize.y);
        computeNoise(parameters);
        captureDemosaic = false;
        Point targetSliced = new Point(rawSliced.x, rawSliced.y);
        if (parameters.fullRawSize != null && parameters.isCropped) {
            targetSliced = new Point(parameters.fullRawSize.x & ~3, parameters.fullRawSize.y & ~3);
        }
        Point rotatedSize = getRotatedCoords(targetSliced);
        // The gain map must be pixel-aligned with the stored SDR base; any
        // size/orientation mismatch displaces the boost field from the scene.
        // Fail loudly -> caller falls back to a plain SDR JPEG.
        if (sdr.getWidth() != rotatedSize.x || sdr.getHeight() != rotatedSize.y) {
            throw new IllegalStateException("SDR/gain-map size mismatch: sdr="
                    + sdr.getWidth() + "x" + sdr.getHeight()
                    + " map=" + rotatedSize.x + "x" + rotatedSize.y);
        }
        GLFormat format = new GLFormat(GLFormat.DataType.FLOAT_16, 4);
        // Unbacked dummy output keeps the GLImage/GLCoreBlockProcessing
        // null-guards happy. Allocate.None skips the full-frame Direct malloc
        // (~490 MB at 64 MP): this pass never draws into the block
        // processor's output buffer (readback goes through outTex), so every
        // GL call below is unchanged. If this pass ever fails, callers fall
        // back to SDR JPEG as before.
        GLImage output = new GLImage(rotatedSize, format, false);
        GLCoreBlockProcessing glproc = new GLCoreBlockProcessing(rotatedSize, output, format, GLDrawParams.Allocate.None);
        // Do not destroy the previous EGL context here: PostPipeline historically
        // leaked the first context until final pipeline.close(), and destroying
        // it before GLTexture re-creation caused SEGV_MAPERR on waffle/Adreno.
        // The leaked context is reclaimed at final pipeline.close().
        glint = new GLInterface(glproc);
        glint.parameters = parameters;

        // Defensive: the measured linear buffer must match the pipeline input size,
        // otherwise the scene sampling is out of bounds and the gain map is garbage.
        if (demosaicLinearSize.x != workSize.x || demosaicLinearSize.y != workSize.y) {
            throw new IllegalStateException("Linear buffer size " + demosaicLinearSize
                    + " does not match workSize " + workSize
                    + "; cannot measure scene plane");
        }

        GLTexture gainTex = null;
        try {

            Point linearSize = new Point(demosaicLinearSize);

            GLTexture linTex;
            if (demosaicLinearHalfFloat) {
                linTex = new GLTexture(
                        linearSize,
                        new GLFormat(GLFormat.DataType.FLOAT_16, 4),
                        null,
                        GL_LINEAR,
                        GL_CLAMP_TO_EDGE);
                linTex.loadHalfFloat(demosaicLinear);
            } else {
                linTex = new GLTexture(
                        linearSize,
                        new GLFormat(GLFormat.DataType.FLOAT_16, 4),
                        demosaicLinear);
            }

            // The CPU snapshot is no longer needed after its upload to linTex.
            releaseDemosaicLinear();

            if (parameters.fullRawSize != null && parameters.isCropped) {
                Point linTarget = new Point(
                        parameters.fullRawSize.x & ~3,
                        parameters.fullRawSize.y & ~3);

                if (!linTarget.equals(linearSize)) {
                    GLTexture linFull = glint.glUtils.interpolate(linTex, linTarget);
                    linTex.close();
                    linTex = linFull;
                }
            }

            // Off-heap staging for the base image upload: GLImage(Bitmap)
            // would allocate a Java-accounted direct copy of the whole bitmap
            // (~258 MB at 64 MP).
            GLTexture sdrTex;
            ByteBuffer sdrStaging = Allocator.allocate(sdr.getByteCount());
            if (sdrStaging != null) {
                try {
                    sdr.copyPixelsToBuffer(sdrStaging);
                    sdrStaging.rewind();
                    sdrTex = new GLTexture(new Point(sdr.getWidth(), sdr.getHeight()),
                            new GLFormat(GLFormat.DataType.SIMPLE_8, 4), sdrStaging, GL_LINEAR, GL_CLAMP_TO_EDGE);
                } finally {
                    Allocator.free(sdrStaging);
                }
            } else {
                GLImage sdrImage = new GLImage(sdr);
                sdrTex = new GLTexture(sdrImage);
            }

            // Lens-shading GainMap for flat-fielding the scene plane (see sceneluma.glsl).
            // Must match the map used on the SDR path (Initial / tofloat) so the ratio
            // is vignette-free. Re-upload from Parameters; the pipeline's GainMap field
            // was deleted by Run()'s closeAll().
            try {
                Point mapSz = mParameters.mapSize != null ? mParameters.mapSize : new Point(1, 1);
                float[] gmArr = mParameters.gainMap;
                if (gmArr == null || gmArr.length < 4) {
                    gmArr = new float[]{1f, 1f, 1f, 1f};
                    mapSz = new Point(1, 1);
                }
                gainTex = new GLTexture(mapSz, new GLFormat(GLFormat.DataType.FLOAT_16, 4),
                        BufferUtils.getFrom(gmArr), GL_LINEAR, GL_CLAMP_TO_EDGE);
            } catch (Exception e) {
                Log.e("PostPipeline", "Failed to upload GainMap for UltraHDR, falling back to identity", e);
                gainTex = new GLTexture(new Point(1, 1), new GLFormat(GLFormat.DataType.FLOAT_16, 4),
                        BufferUtils.getFrom(new float[]{1f, 1f, 1f, 1f}), GL_LINEAR, GL_CLAMP_TO_EDGE);
            }

            // sdrTex is the actual stored base that the gain map will modify.
            // Use its dimensions as the authoritative output coordinate space.
            final Point sdrSize = sdrTex.mSize;

            // Ceiling division preserves the complete source extent, including
            // partial right/bottom blocks for non-divisible dimensions.
            int gw = Math.max(1, (sdrSize.x + down - 1) / down);
            int gh = Math.max(1, (sdrSize.y + down - 1) / down);

            // Scene luma is reduced directly onto the final gain-map grid.
            GLTexture lTex = new GLTexture(new Point(gw, gh),
                    new GLFormat(GLFormat.DataType.FLOAT_16, 4));
            lTex.BufferLoad();

            GLProg prog = glint.glProgram;
            prog.useAssetProgram("ultrahdr/sceneluma");
            prog.setTexture("InputBuffer", linTex);
            prog.setTexture("GainMap", gainTex);
            prog.setVar("rotate", rotationIndex());
            prog.setVar("mirror", parameters.mirror ? 1 : 0);
            prog.setVar("cropSize", cropSize);
            prog.setVar("rawSize", mParameters.rawSize);
            prog.setVar("uLinFullSize", sdrSize.x, sdrSize.y);
            prog.setVar("uLinGridSize", gw, gh);
            GLES30.glDisable(GLES30.GL_SCISSOR_TEST);
            GLES30.glBindFramebuffer(GLES30.GL_FRAMEBUFFER, lTex.mBuffer);
            GLES30.glViewport(0, 0, gw, gh);
            prog.draw();
            checkGlError("scene-luma draw");
            // linTex is consumed: release it now instead of with the group
            // below, so its ~512 MB (64 MP) doesn't overlap the histogram,
            // downsample and gain-map draws. Nothing below reads it.
            linTex.close();

            // Preserve the original full-resolution SDR texture at down == 1.
            // This keeps the established <=16 MP path unchanged. At reduced
            // resolutions, create a matched linear-light reduction instead of
            // a GL_LINEAR blit, since the footprint will not match lTex.
            GLTexture sdrSmall;
            if (down == 1) {
                sdrSmall = sdrTex;
            } else {
                sdrSmall = new GLTexture(new Point(gw, gh),
                        new GLFormat(GLFormat.DataType.FLOAT_16, 4));
                sdrSmall.BufferLoad();

                sdrTex.Bufferize();
                prog.useAssetProgram("ultrahdr/downsample_sdr");
                prog.setTexture("InputBuffer", sdrTex);
                prog.setVar("uGridSize", gw, gh);
                GLES30.glBindFramebuffer(GLES30.GL_FRAMEBUFFER, sdrSmall.mBuffer);
                GLES30.glViewport(0, 0, gw, gh);
                prog.draw();
                checkGlError("Ultra HDR SDR matched downsample draw");
                sdrTex.close();
            }

            // Anchor: medians of the rendering and of the scene plane. Median
            // (not top-percentile) anchoring is required - with large blown
            // regions both top percentiles land inside the same saturated area
            // and would cancel out, while matched medians keep the scene/render
            // ratio growing monotonically toward saturation.
            final int histSize = 256;
            float lMed;
            float sMedLin;
            GLHistogram hist = new GLHistogram(prog, histSize);
            try {
                lMed = Math.max(histogramMedian(hist.Compute(lTex), histSize), 1e-4f);
                float sMedDisp = histogramMedian(hist.Compute(sdrSmall), histSize);
                sMedLin = srgbToLinear(sMedDisp);
            } finally {
                hist.close();
            }
            float anchor;
            if (sceneWhiteRaw > 0f) {
                // Tonemapping white-point anchor: gain 0 exactly where the
                // SDR reaches display white, pushing only the scene headroom
                // above it. Scene-independent and immune to the SDR midtone
                // choice (the median anchor's implied scene white collapses to
                // uselessness when the tonemapping renders a dark midtone).
                anchor = 1.0f / sceneWhiteRaw;
                Log.d("PostPipeline", "UltraHDR scene-white anchor:" + anchor
                        + " sceneWhiteRaw:" + sceneWhiteRaw
                        + " Lmed:" + lMed + " SmedLin:" + sMedLin);
            } else {
                anchor = sMedLin / lMed;
                Log.d("PostPipeline", "UltraHDR median anchor:" + anchor
                        + " Lmed:" + lMed + " SmedLin:" + sMedLin);
            }

            // Gain-map output is scalar. Store only its red channel as R8;
            // gainmap.glsl writes the same encoded value to RGB, so retaining
            // all four RGBA8 components is redundant.
            GLTexture outTex = new GLTexture(new Point(gw, gh),
                    new GLFormat(GLFormat.DataType.SIMPLE_8, 1));
            outTex.BufferLoad();

            prog.useAssetProgram("ultrahdr/gainmap");
            prog.setTexture("InputBuffer", sdrSmall);
            prog.setTexture("LBuffer", lTex);
            prog.setVar("uAnchor", anchor);
            prog.setVar("uDown", 1);
            prog.setVar("uScale", scale);
            prog.setVar("uEps", GainMapComputer.DECODE_OFFSET);
            GLES30.glBindFramebuffer(GLES30.GL_FRAMEBUFFER, outTex.mBuffer);
            GLES30.glViewport(0, 0, gw, gh);
            prog.draw();
            checkGlError("gain-map comparison draw");

            // Release the GPU resources before the CPU-side bitmap work.
            // (linTex was already released right after the scene-luma draw.)
            sdrSmall.close();
            lTex.close();

            // R8 cannot be read directly into an ARGB_8888 Bitmap because
            // Android bitmaps require four bytes per pixel. Read the scalar
            // gain bytes, then expand each value to opaque grayscale ARGB.
            //
            // gmBmp remains mutable and at the final logical gain-map size,
            // allowing GainMapComputer.compute() to normalize it in place.
            // Adapted to HEAD: retains linTex.close() from newzoom and keeps
            // the R8 readback (gw*gh, SIMPLE_8/1) on the unpacked lTex path.
            Bitmap gmBmp = Bitmap.createBitmap(gw, gh, Bitmap.Config.ARGB_8888);
            ByteBuffer gm = Allocator.allocate(gw * gh);
            if (gm == null) {
                throw new IllegalStateException(
                        "Unable to allocate R8 gain-map readback buffer: "
                                + gw + "x" + gh);
            }
            try {
                outTex.textureBuffer(
                        new GLFormat(GLFormat.DataType.SIMPLE_8, 1),
                        gm);
                gm.rewind();

                int[] row = new int[gw];
                for (int y = 0; y < gh; y++) {
                    for (int x = 0; x < gw; x++) {
                        int v = gm.get() & 0xFF;
                        row[x] = 0xFF000000 | (v << 16) | (v << 8) | v;
                    }
                    gmBmp.setPixels(row, 0, gw, 0, y, gw, 1);
                }
            } finally {
                Allocator.free(gm);
            }
            outTex.close();

            if (gainTex != null) {
                try { gainTex.close(); } catch (Exception ignored) {}
                gainTex = null;
            }
            // The GPU map is already at its final grid, so the box filter
            // must not run again (down = 1).
            Allocator.logStage("PostPipeline", "post-gainmap-render");
            return new GainMapRaw(gmBmp, gw, gh, 1, scale);
        } finally {
            if (gainTex != null) {
                try { gainTex.close(); } catch (Exception ignored) {}
            }
            GLTexture.closeAll();
            // Consume-once: the snapshot is only needed for this pass.
            releaseDemosaicLinear();
        }
    }

    @Override
    public void close() {
        // Safety net for paths where the gain-map pass never ran.
        releaseDemosaicLinear();
        super.close();
    }

    private void checkGlError(String what) {
        int err = GLES30.glGetError();
        if (err != GLES30.GL_NO_ERROR) {
            Log.e("PostPipeline", "GL error 0x" + Integer.toHexString(err) + " in " + what);
        }
    }

    /** Rotation index used by the rotate-style shaders: 90->3, 180->2, 270->1, else 0. */
    private int rotationIndex() {
        switch (getRotation()) {
            case 90: return 3;
            case 180: return 2;
            case 270: return 1;
            default: return 0;
        }
    }

    /**
     * Median of a {@link GLHistogram} result across RGB channels: the bin
     * where the cumulative count from the top crosses half of all samples.
     * Returns the bin value normalized to [0,1].
     */
    private static float histogramMedian(int[][] result, int histSize) {
        long total = 0L;
        for (int i = 0; i < histSize; i++) {
            total += (long) result[0][i] + (long) result[1][i] + (long) result[2][i];
        }
        if (total <= 0L) return 0f;
        final long threshold = total / 2L;
        long acc = 0;
        for (int i = histSize - 1; i >= 0; i--) {
            acc += (long) result[0][i] + (long) result[1][i] + (long) result[2][i];
            if (acc > threshold) return (float) i / (float) (histSize - 1);
        }
        return 1f;
    }

    private static float srgbToLinear(float c) {
        c = Math.min(Math.max(c, 0f), 1f);
        return c <= 0.04045f ? c / 12.92f : (float) Math.pow((c + 0.055) / 1.055, 2.4);
    }

    public static class GainMapRaw {
        public final Bitmap bitmap;
        public final int w;
        public final int h;
        public final int down;
        public final float scale;
        GainMapRaw(Bitmap bitmap, int w, int h, int down, float scale) {
            this.bitmap = bitmap;
            this.w = w;
            this.h = h;
            this.down = down;
            this.scale = scale;
        }
    }

    private void BuildDefaultPipeline() {
        boolean nightMode = PhotonCamera.getSettings().selectedMode == CameraMode.NIGHT;
        add(new Bayer2Float());
        add(new KernelNetPrep());
        // add(new ExposureFusionBayer2());
        switch (PhotonCamera.getSettings().cfaPattern) {
            case -2: {
                add(new DemosaicQUAD());
                break;
            }
            case 4: {
                add(new MonoDemosaic());
                break;
            }
            default: {
                if (PhotonCamera.getSettings().hdrxNR) {
                }

                if (mSettings.alignAlgorithm != 2) {
                    switch (demosaicingMethod) {
                        case 0:
                            add(new Demosaic());
                            break;
                        default:
                            add(new Amaze());
                            break;
                    }
                }
                if (PhotonCamera.getSettings().hdrxNR) {
                    add(new ESD3D2(true));
                }
                break;
            }
        }
        add(new ABLC());
        if ("off".equals(tonePipeline)) {
            // No tone/color stage: the linear camera RGB passes through
            // untouched. LinearExposure draws nothing but keeps the Ultra HDR
            // linear-scene snapshot duty alive.
            add(new LinearExposure());
        } else if ("sky".equals(tonePipeline)) {
            add(new LinearExposure());
            add(new HeadroomRender());
        } else {
            // Default: curve-based AE - AutoExposureCurve
            // bakes the display exposure response into
            // PostPipeline.exposureCurve, Initial samples it inside its own
            // pass (one full-res draw less than the former
            // Initial + AutoExposure pair).
            add(new AutoExposureCurve());
            if ("new".equals(tonePipeline)) {
                add(new ModernInitial());
            } else {
                add(new Initial());
            }
        }
        // Crops expand to the full-frame output size BEFORE the local-contrast
        // and sharpening passes, so those run at output resolution like any
        // other shot - otherwise their crop-resolution halos get magnified by
        // the zoom factor and read as pixelation along edges.
        add(new UpscaleCrop());
        add(new LocalLaplacian2());
        add(new CaptureSharpening());
        add(new CorrectingFlow());
        add(new Sharpen2());
        add(new RotateWatermark(getRotation()));
    }
}
